apiVersion: v1
kind: Pod
metadata:
  name: gh-pod
  namespace: grocery-hack
  labels:
    app: omfp
spec:
  containers:
    - name: grocery-hack-app
      image: seth4ibm/groceryhack:v1
      ports:
      - containerPort: 3000
        name: http